#!/usr/bin/env ruby
# frozen_string_literal: true

# Build edoxen-data/registers/venues.yaml — a VenueRegister derived
# from the inline `venues:` blocks across edoxen-data/meetings/*.yaml.
#
# Registers are currently inert reference data: meetings keep their
# inline venues until the published toolchain supports ref resolution
# end-to-end. Re-run after any meeting venue change to keep the
# register in sync.

require "yaml"

ROOT = File.expand_path("..", __dir__)
SCOPE = "oiml"
URN_PREFIX = "urn:edoxen:venue:#{SCOPE}:"

physical = {}
virtual_seen = false

Dir.glob(File.join(ROOT, "edoxen-data", "meetings", "*.yaml")).sort.each do |path|
  (YAML.load_file(path)["venues"] || []).each do |v|
    if v["kind"] == "virtual"
      virtual_seen = true
      next
    end
    key = v["unlocode"]
    next unless key

    physical[key] ||= { "unlocode" => v["unlocode"], "country_code" => v["country_code"] }
  end
end

venues = physical.keys.sort.map do |unlocode|
  {
    "urn" => "#{URN_PREFIX}#{unlocode.downcase}",
    "kind" => "physical",
    "unlocode" => unlocode,
    "country_code" => physical[unlocode]["country_code"],
  }
end
venues << { "urn" => "#{URN_PREFIX}virtual", "kind" => "virtual" } if virtual_seen

register = {
  "scope" => SCOPE,
  "title" => [{ "spelling" => "eng", "value" => "OIML venue register" }],
  "venues" => venues,
}

header = <<~YAML
  # VenueRegister — generated by scripts/build-venue-register.rb
  # Source of truth for OIML meeting venues. Inert until
  # ref-resolution lands in the published toolchain; meetings keep
  # inline venues meanwhile.
YAML

out = File.join(ROOT, "edoxen-data", "registers", "venues.yaml")
File.write(out, header + YAML.dump(register))
puts "Wrote #{out}: #{venues.size} venues (#{physical.size} physical, #{virtual_seen ? 1 : 0} virtual)"
