#!/usr/bin/env ruby
# frozen_string_literal: true

# Updates meetings/*.yaml to reference available minutes/*.yaml.
#
# For every meeting YAML in meetings/, if a corresponding
# minutes/ciml-{N}-{lang}.yaml exists, add the minutes URN to the
# meeting's `minutes: []` collection.
#
# For meetings with minutes but no meeting YAML (e.g., pre-39 CIML
# meetings that predate the manifest), generate a skeleton meeting
# YAML derived from the minutes file.
#
# Idempotent.

require "yaml"
require "fileutils"
require "set"

ROOT = File.expand_path("..", __dir__)
MEETINGS_DIR = File.join(ROOT, "meetings")
MINUTES_DIR = File.join(ROOT, "minutes")

def each_minutes_file
  return enum_for(:each_minutes_file) unless block_given?

  Dir.glob(File.join(MINUTES_DIR, "ciml-*.yaml")).sort.each do |path|
    basename = File.basename(path, ".yaml")
    if basename =~ /\Aciml-(\d+)-([a-z]{3})\z/
      yield(path, $1.to_i, $2)
    end
  end
end

# Step 1: index minutes by meeting ordinal.
minutes_by_ordinal = Hash.new { |h, k| h[k] = [] }
each_minutes_file do |path, ordinal, lang|
  data = YAML.safe_load(File.read(path))
  minutes_by_ordinal[ordinal] << {
    "urn" => data["urn"],
    "language_code" => data["language_code"],
    "source_doc" => data["source_doc"],
  }
end

# Step 2: update existing meeting YAMLs.
existing_meetings = Dir.glob(File.join(MEETINGS_DIR, "ciml-*.yaml")).sort
existing_ordinals = existing_meetings.map do |p|
  File.basename(p, ".yaml")[/\Aciml-(\d+)\z/, 1].to_i
end

existing_meetings.each do |path|
  data = YAML.safe_load(File.read(path))
  ordinal = data["ordinal"]
  next unless ordinal

  refs = minutes_by_ordinal.delete(ordinal)
  next if refs.nil? || refs.empty?

  minutes_field = (data["minutes"] || []).dup
  existing_urns = minutes_field.map { |m| m["urn"] }.to_set

  refs.each do |ref|
    next if existing_urns.include?(ref["urn"])

    entry = {
      "urn" => ref["urn"],
      "language_code" => ref["language_code"],
      "script" => "Latn",
    }
    # source_doc is optional in the schema; omit when nil so we don't
    # emit `source_doc: null` which fails the `type: string` check.
    entry["source_doc"] = ref["source_doc"] if ref["source_doc"] && !ref["source_doc"].empty?
    minutes_field << entry
  end

  data["minutes"] = minutes_field.map do |entry|
    if entry["source_doc"].nil? || entry["source_doc"].to_s.empty?
      entry = entry.dup
      entry.delete("source_doc")
    end
    entry
  end
  File.write(path, "---\n# Auto-updated by scripts/link_minutes_to_meetings.rb.\n" +
                   data.to_yaml.sub(/^---\s*$/, "").lstrip)
  puts "Updated meetings/ciml-#{ordinal}.yaml (#{refs.size} minutes refs)"
end

# Step 3: create skeleton meetings for ordinals with minutes but no meeting YAML.
minutes_by_ordinal.each do |ordinal, refs|
  slug = "ciml-#{ordinal}"
  out_path = File.join(MEETINGS_DIR, "#{slug}.yaml")

  langs = refs.map { |r| r["language_code"] }
  localizations = langs.map do |lang|
    {
      "language_code" => lang,
      "script" => "Latn",
      "title" => "#{ordinal}th CIML Meeting (skeleton from minutes)",
      "general_area" => "",
    }
  end

  data = {
    "identifier" => [{ "prefix" => "CIML", "number" => ordinal.to_s }],
    "urn" => "urn:oiml:ciml:meeting:#{slug}",
    "type" => "plenary",
    "status" => "completed",
    "ordinal" => ordinal,
    "localizations" => localizations,
    "minutes" => refs.map { |r|
      entry = {
        "urn" => r["urn"],
        "language_code" => r["language_code"],
        "script" => "Latn",
      }
      entry["source_doc"] = r["source_doc"] if r["source_doc"] && !r["source_doc"].empty?
      entry
    },
    "resolution_refs" => ["urn:oiml:ciml:resolution-collection:#{slug}-resolutions"],
  }
  File.write(out_path, "---\n# Auto-generated by scripts/link_minutes_to_meetings.rb.\n" +
                       data.to_yaml.sub(/^---\s*$/, "").lstrip)
  puts "Created #{out_path} (skeleton; #{refs.size} minutes refs)"
end

puts "\nDone."
