# frozen_string_literal: true

# Parse the OIML Development Council (DC) 2004 decisions from the
# OCR'd markdown at:
#   reference-docs/ocr/md/2004-oimldc-decisions-en.md
#   reference-docs/ocr/md/2004-oimldc-decisions-fr.md
#
# Output: resolutions/dc-1-2004-decisions.yaml (v2 edoxen DecisionCollection).
#
# The DC decisions PDF has 4 numbered items, each beginning with a
# line like:
#   "1     The Development Council thanked Mr Seiler..."
#   "2     The Development Council noted Mr Seiler's report..."
# The text after the number is both the title (truncated for display)
# and the action message.

require "yaml"
$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "oiml/resolutions_data"

module ResolutionsData
  module ParseDcDecisions
    ROOT = File.expand_path("..", __dir__)
    OCR_DIR = File.join(ROOT, "reference-docs", "ocr", "md")
    OUT_DIR = File.join(ROOT, "resolutions")
    OUT_FILE = File.join(OUT_DIR, "dc-1-2004-decisions.yaml")

    DC_PREFIX = "DC"
    DC_YEAR = "2004"
    DC_MEETING_SLUG = "dc-1-2004"
    DC_MEETING_URN = "urn:oiml:dc:meeting:dc-1-2004"

    # A DC OCR row looks like:
    #   <digits><2+spaces><body text>
    DC_ROW_RE = /\A\s*(\d{1,2})\s{2,}(.+)\z/.freeze

    def self.parse_markdown(path, lang_code)
      return [] unless path && File.file?(path)

      text = File.read(path)
      items = []
      text.each_line do |raw|
        line = raw.rstrip
        if (m = line.match(DC_ROW_RE))
          number = m[1]
          body = m[2].strip
          next if body.empty?
          items << { "number" => number, "body" => body }
        elsif items.any? && line.start_with?("      ")
          # Continuation line (6+ leading spaces) — append to the
          # previous item's body.
          items.last["body"] << " " << line.strip
        end
      end
      items
    end

    def self.build_decision(item, en_text, fr_text)
      number = "#{DC_YEAR}/#{item['number']}"
      {
        "identifier" => [{ "prefix" => DC_PREFIX, "number" => number }],
        "doi" => "10.63493/resolutions/dc#{DC_YEAR}#{item['number']}",
        "urn" => "urn:oiml:dc:resolution:#{number}",
        "dates" => [{ "date" => "2004-10-25", "type" => "decided" }],
        "localizations" => [
          build_localization("eng", en_text),
          build_localization("fra", fr_text),
        ].compact,
      }
    end

    def self.build_localization(lang_code, body)
      return nil if body.nil? || body.strip.empty?

      # Title: first sentence (or first 80 chars) of the body.
      title = body.split(/(?<=[.!?])\s+/).first || body
      title = title[0, 80].rstrip
      {
        "language_code" => lang_code,
        "title" => title,
        "subject" => "Development Council",
        "considerations" => [],
        "actions" => [
          {
            "type" => "resolution",
            "message" => body,
            "date_effective" => { "date" => "2004-10-25", "type" => "decided" },
          },
        ],
        "approvals" => [],
      }
    end

    def self.run
      en_path = File.join(OCR_DIR, "2004-oimldc-decisions-en.md")
      fr_path = File.join(OCR_DIR, "2004-oimldc-decisions-fr.md")

      en_items = parse_markdown(en_path, "eng")
      fr_items = parse_markdown(fr_path, "fra")

      # Match by number; EN is the canonical ordering.
      by_num = {}
      en_items.each { |i| by_num[i["number"]] = [i["body"], nil] }
      fr_items.each do |i|
        by_num[i["number"]] ||= [nil, nil]
        by_num[i["number"]][1] = i["body"]
      end

      decisions = by_num.keys.sort_by { |n| n.to_i }.map do |num|
        (en, fr) = by_num[num]
        build_decision({ "number" => num }, en, fr)
      end

      data = {
        "metadata" => {
          "source" => "OIML Development Council",
          "meeting_urn" => DC_MEETING_URN,
          "city" => "DEBER",
          "country_code" => "DE",
          "title_localized" => [
            { "language_code" => "eng", "title" => "1st OIML Development Council — Decisions (EN)" },
            { "language_code" => "fra", "title" => "1er Conseil de Développement de l'OIML — Décisions (FR)" },
          ],
        },
        "decisions" => decisions,
      }

      FileUtils.mkdir_p(OUT_DIR)
      File.write(OUT_FILE, "---\n# Auto-generated by scripts/parse_dc_decisions.rb.\n#{data.to_yaml.sub(/\A---\s*\n/, "")}")
      puts "Wrote #{OUT_FILE} (#{decisions.size} decisions)"
    end
  end
end

require "fileutils"
ResolutionsData::ParseDcDecisions.run
